// frontend/app/user/create/login/page.tsx
'use client';
import {
  TextInput,
  PasswordInput,
  Button
} from '@mantine/core';
import { useState } from 'react';
import {FormEvent} from 'react';
import axios from 'axios';

export default function Login()
{
  const [usernameOrEmail, setUsernameOrEmail] = useState('')
  const [password, setPassword] = useState('')

  const onSubmit = (event: FormEvent) => {
      
  }

  return (
    <div>
      <h1>Welcome Back!</h1>
      <h2>Log In</h2>
      <form>
	<TextInput onInput={(e)=>{setUsernameOrEmail(e.currentTarget.value)}} id='username_or_email' variant="filled" radius="xs" label="Username or Email" withAsterisk placeholder="Enter username or email" required/>
	<PasswordInput onInput={(e)=>{setPassword(e.currentTarget.value)}} radius="xs" label="Password" withAsterisk placeholder="Input placeholder" required/>
	<Button type='submit'>Log In</Button>
      </form>
    </div>
  );
}

// svelte/src/routes/user/actions/login/+page.svelte
<script lang="ts">
  import Form from "$lib/Components/Form.svelte";
  import BackHeader from "$lib/Components/BackHeader.svelte";
</script>
<BackHeader title='Log In'/>
<Form method='post'>
  <label class="label">
    <span>Username or Email<span class="text-red-500">*</span></span>
    <input class="input" type="text" name='username_or_email' placeholder="Enter Username or Email" required />
  </label>
  <label class="label">
    <span>Password<span class="text-red-500">*</span></span>
    <input class="input" type="password" name='password' placeholder="Enter Password" required />
  </label>
  <button class='btn variant-filled-primary font-bold' type='submit'>Log In</button>
</Form>
