// frontend/app/user/create/login/page.tsx
import * as React from 'react';
import { 
  Button,
  TextField,
  Link as MaterialLink,
  OutlinedInput,
} from '@mui/material';
import Link from 'next/link';

export default function LoginPage()
{
  return (
    <main className='flex flex-col w-full h-full px-4 pt-5 items-center'>
      <form className='flex flex-col w-full py-4 px-4 items-center'>
	<h1 className='text-4xl'>Log In</h1>
	<TextField className='text-white bg-white rounded w-full mt-4' id='username_or_email' variant='filled' label='Username or Email' />
	<TextField className='bg-white rounded text-black w-full mt-4' id='password' variant='filled' label='Password' type='password' />
	<Button variant='contained' className='w-min text-nowrap mt-10'>Log In</Button>
      </form>
      <p className='mt-5'>Don't Have an Account? <Link href='/user/create/signup'><MaterialLink>Sign Up</MaterialLink></Link></p>
    </main>
  )
}

// rosen_svelte/src/routes/account/login/+page.svelte
<script lang="ts">
	import {enhance} from '$app/forms';
	import {goto} from '$app/navigation';
  import type { PageData, ActionData, PageServerLoad } from './$types';

  export let data: PageServerLoad;

  export let form: ActionData;

</script>
<h1
class="text-white text-4xl mb-8"
style="font-weight: 300;"
>Log In</h1>
<form
class="flex flex-col flex-start w-full sm:max-w-full max-w-xs"
method="post"
use:enhance={()=>{
  return async ({result}) => {
    if (result.data.redirect)
    {
      goto(result.data.redirect)
    }
  }
}}
>
  <label for="usernameOrEmail" > Username or Email </label>
  <input id="usernameOrEmail" name="username_email" type="text" required>

  <label for="password" > Password </label>
  <input id="password" name="password" type="password" required>

  <input id="submit" type="submit" value="Log In" class="mt-4 w-min button-class ml-auto mr-auto">

</form>
<p
class="mt-2"
>
  Don't have account? 
  <a
  class="link"
  href="/account/signup"
  >
  Sign Up
  </a>
</p>
